---
openshift_cluster_content:
- object: base
  content:
    - name: non-prod
      template: "{{ inventory_dir }}/../templates/project/project-request-template.yml"
      params: "{{ inventory_dir }}/../params/project/{{ non_prod_namespace }}"
      action: create
      tags:
      - project-request
      - base
    - name: prod
      template: "{{ inventory_dir }}/../templates/project/project-request-template.yml"
      params: "{{ inventory_dir }}/../params/project/{{ prod_namespace }}"
      action: create
      tags:
      - project-request
      - base
- object: build
  content:
    - name: pipeline-cd
      template: "{{ inventory_dir }}/../templates/game-room/pipeline-template.yml"
      params: "{{ inventory_dir }}/../params/game-room/pipeline-cd"
      namespace: "{{ non_prod_namespace }}"
      tags:
      - game-room
      - pipeline-cd
      - build
    - name: unique-build
      template: "{{ inventory_dir }}/../templates/game-room/build-source-template.yml"
      params: "{{ inventory_dir }}/../params/game-room/build"
      namespace: "{{ non_prod_namespace }}"
      tags:
      - game-room
      - unique-build
      - build
    - name: jenkins-deploy
      template: "{{ inventory_dir }}/../templates/game-room/jenkins-template.yml"
      params: "{{ inventory_dir }}/../params/game-room/pipeline-cd"
      namespace: "{{ non_prod_namespace }}"
      tags:
      - jenkins-deploy
      - unique-build
      - build
- object: deploy-non-prod
  content:
    - name: service
      template: "{{ inventory_dir }}/../templates/game-room/deploy-template.yml"
      params: "{{ inventory_dir }}/../params/game-room/deploy-non-prod"
      namespace: "{{ non_prod_namespace }}"
      tags:
      - game-room
      - service
      - non-prod
    - name: cache
      template: "{{ inventory_dir }}/../templates/game-room/redis-template.yml"
      params: "{{ inventory_dir }}/../params/game-room/redis"
      namespace: "{{ non_prod_namespace }}"
      tags:
      - game-room
      - cache
      - non-prod
    - name: data-grid
      template: "{{ inventory_dir }}/../templates/game-room/data-grid-template.yml"
      params: "{{ inventory_dir }}/../params/game-room/data-grid"
      namespace: "{{ non_prod_namespace }}"
      tags:
      - game-room
      - data-grid
      - non-prod
- object: deploy-prod
  content:
    - name: service-blue
      template: "{{ inventory_dir }}/../templates/game-room/deploy-bg-template.yml"
      params: "{{ inventory_dir }}/../params/game-room/deploy-prod-blue"
      namespace: "{{ prod_namespace }}"
      tags:
      - game-room
      - blue
      - service
      - prod
    - name: service-green
      template: "{{ inventory_dir }}/../templates/game-room/deploy-bg-template.yml"
      params: "{{ inventory_dir }}/../params/game-room/deploy-prod-green"
      namespace: "{{ prod_namespace }}"
      tags:
      - game-room
      - green
      - service
      - prod
    - name: cache
      template: "{{ inventory_dir }}/../templates/game-room/redis-template.yml"
      params: "{{ inventory_dir }}/../params/game-room/redis"
      namespace: "{{ prod_namespace }}"
      tags:
      - game-room
      - cache
      - prod
    - name: data-grid
      template: "{{ inventory_dir }}/../templates/game-room/data-grid-template.yml"
      params: "{{ inventory_dir }}/../params/game-room/data-grid"
      namespace: "{{ prod_namespace }}"
      tags:
      - game-room
      - data-grid
      - prod
