---
- name: Deploy Dino dash backend
  hosts: app
  vars:
    non_prod_namespace: dino-dash-non-prod
    prod_namespace: dino-dash-prod
  tasks:
  - include_role:
      name: openshift-applier/roles/openshift-applier
